[build]
  publish = "/"
  functions = "netlify/functions"

[[redirects]]
  from = "/"
  to = "/home.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  [functions.fitbit-fetch]
    schedule = "0 0 */13 * *"  # Runs every 13 days at midnight