[build]
  publish = "public"
  functions = "netlify/functions"
  command = "npm run build"

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**"]

[dev]
  framework = "#static"
  staticServerPort = 8888
  functionsPort = 9999
  port = 3001
  publish = "public"