[build]
  publish = "public"
  functions = "netlify/functions"
  command = "npm run build"

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**"]

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  framework = "#static"
  targetPort = 8888
  port = 3000
  publish = "public"